### ISSUE TITLE
Qui sommes nous? 

### ISSUE THREAD

**Issue by MorganeGrenes** [WildCodeSchool/tours-php-2009-project2-quizzy#21]
Il y a des images qui ne sont pas chargées dans la page "qui sommes nous?" :)

![image](https://user-images.githubusercontent.com/66020799/100232354-8fa3b500-2f28-11eb-9051-8a56f167377d.png)

**Comment by rickifox** [comment]
Alors moi je n'aurais pas su qu'il y avait des images sans ce commentaire ^^'

**Comment by rickifox** [comment]
![image](https://user-images.githubusercontent.com/65194501/100233601-43f20b00-2f2a-11eb-9b78-8cd2149b13c2.png)

**Comment by LucyMerlier** [comment]
effectivement il manque encore nos belles bouilles ^_^

**Comment by thocle86** [comment]
De plus, le texte "Qui somme nous" est dans FAQ, il aurait été bien de l'avoir dans "A propose de nous"
