### ISSUE TITLE
entre 3 et 200 caractères

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-quizzy#24]
3 étant exclus n'y aurais t-il pas une formulation plus explicite?

**Comment by rickifox** [comment]
réponses de 3 à 200 caractères par exemple mais à voir avec les autres ce n'est que mon ressenti et pour trois caractères ce n'est pas pour le temps passé à reformuler ^^

**Comment by LucyMerlier** [comment]
thx for the issue, we're gonna crarify this ;)
