### ISSUE TITLE
Une seul grande colonne ?

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-quizzy#25]
Charte graphique très agréable, interface simple d'utilisation, petite suggestion pour l'UX: avec l'espace disponnible sur desktop ne serait -il pas possible d'afficher les réponses côte côte pour toutes les avoir sous les yeux et ne pas avoir à scroller ?
et sur mobile ne pourrait-on pas réduire ou occulter le logo le temps de répondre par exemple ?

**Comment by LucyMerlier** [comment]
good issue ;)

**Comment by KevinRoig** [comment]
Maybe having more difference between answers and the other boxes (pass and add), visually speaking? 
Also, do we really need "FAQ" and so on second page, because no time to click on!
